package pawsshop;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {
    
    private String userType;
    
    // Creating a list to store all user (both Cahiers & Manager)
    public static ArrayList<User> userList = new ArrayList<>();
    
    public static void saveUserList() {
        try (ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("userList.dat"))) {
            out.writeObject(userList);  // Serialize and save userList
            System.out.println("User list saved successfully.");
        } catch (IOException e) {
            System.err.println("Error saving user list: " + e.getMessage());
        }
    }

    // Method to load the userList from a file
    public static void loadUserList() {
        try (ObjectInputStream in = new ObjectInputStream(new FileInputStream("userList.dat"))) {
            userList = (ArrayList<User>) in.readObject();  // Deserialize the list
            System.out.println("User list loaded successfully.");
        } catch (IOException | ClassNotFoundException e) {
            System.err.println("Error loading user list: " + e.getMessage());
        }
    }
       

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        loadUserList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 220, -1));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, -1));

        submitBtn.setBackground(new java.awt.Color(0, 153, 153));
        submitBtn.setForeground(new java.awt.Color(0, 0, 0));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    public String login(){
        
        String username = usernameField.getText();
        String password = passwordField.getText();
        
/**     Creating some users (Cashier & Manager) and adding to the list.
 *      
 *      The following Users have been added and saved to userList.dat file the fist time the code was run.
 *      Therefore commenting this section to avoid duplication and for visibility.
 * 
        userList.add(new Cashier("Arun", "5555", "arun", "arun" , "001"));
        userList.add(new Manager("Peniel", "7777", "peniel", "peniel" ,"001"));   
         
        saveUserList();
**/        
        // Loops through the list and validate login credentials
        for(User user : userList){
            if(username.equals(user.getUsername()) && password.equals(user.getPassword())){
               
                 // If the user is a Manager
                if (user instanceof Manager) {
                    // Open the Manager interface
                    ManagerFrame managerFrame = new ManagerFrame(this);
                    managerFrame.setVisible(true);
//                    CashierFrame cashierFrame = new CashierFrame(this);
//                    cashierFrame.setVisible(true);
                    this.dispose();  // Close the login screen
                    userType = "Manager";
                }
            
                 // If the user is a Cashier (but not a Manager)
                else if (user instanceof Cashier) {
                    // Open the Cashier interface
                    CashierFrame cashierFrame = new CashierFrame(this);
                    cashierFrame.setVisible(true);
                    this.dispose();  // Close the login screen
                    userType = "Cashier";
                }
                
                
                break; // To exit loop when login is successful
            }
//              else {
//                JOptionPane.showMessageDialog(null, "Invalid Credentials! \n Please try again.");
//                break;
//            }
        }
        
        
        return userType;
    }

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        userType =  login();
    }//GEN-LAST:event_submitBtnActionPerformed

    public String getUserType(){
       return userType;
    }
    

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
